"""
VoiceFlow Local - Configuration Settings

Generated by the settings window.
"""

import os

# Hotkey
HOTKEY = 'ctrl+space'
TOGGLE_MODE = False

# Whisper model
MODEL_SIZE = 'medium'
DEVICE = 'cuda'
COMPUTE_TYPE = 'float16'
LANGUAGE = None
LANGUAGE_CHOICE = 'auto detect'
BEAM_SIZE = 5
PRELOAD_MODEL_ON_START = False

# Text cleanup
REMOVE_FILLERS = True
FILLER_WORDS = ['um', 'uh']
FIX_SELF_CORRECTIONS = True
AUTO_CAPITALIZE = True
ENABLE_VOICE_COMMANDS = True

# Storage
HISTORY_LIMIT = 50
AUTO_SAVE = True
LOG_FORMAT = 'JSON lines'
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR = os.path.join(BASE_DIR, 'models')
TEMP_DIR = os.path.join(BASE_DIR, 'temp')
LOG_FILE = os.path.join(BASE_DIR, 'voiceflow_log.txt')

# Behaviour
START_WITH_WINDOWS = False
SHOW_NOTIFICATIONS = True
SILENCE_THRESHOLD_SEC = 3
DEBUG_MODE = False
